package injection

/*
#cgo CFLAGS: -x objective-c -fobjc-arc
#cgo LDFLAGS: -framework AppKit

#import <AppKit/AppKit.h>

static NSPasteboard *pasteboardNamed(_GoString_ name) {
	if (_GoStringLen(name) == 0) return NSPasteboard.generalPasteboard;
	return [NSPasteboard pasteboardWithName:[[NSString alloc] initWithBytes:_GoStringPtr(name)
	                                                                 length:_GoStringLen(name)
	                                                               encoding:NSUTF8StringEncoding]];
}

static long pbChangeCount(_GoString_ name) {
	@autoreleasepool {
		return pasteboardNamed(name).changeCount;
	}
}

// pbCopyItems returns each item as an array alternating UTF-8 type name and
// data. dataForType: makes the source app render lazily promised data, which
// is slow for huge copies but is the only way to keep them.
static CFArrayRef pbCopyItems(_GoString_ name) {
	@autoreleasepool {
		NSMutableArray *items = [NSMutableArray array];
		for (NSPasteboardItem *item in pasteboardNamed(name).pasteboardItems) {
			NSMutableArray *entries = [NSMutableArray array];
			for (NSPasteboardType type in item.types) {
				NSData *data = [item dataForType:type];
				if (data) [entries addObjectsFromArray:@[[type dataUsingEncoding:NSUTF8StringEncoding], data]];
			}
			if (entries.count) [items addObject:entries];
		}
		return (CFArrayRef)CFBridgingRetain(items);
	}
}

static void *pbNewItems(void) {
	return (__bridge_retained void *)[NSMutableArray new];
}

static void *pbAddItem(void *items) {
	NSPasteboardItem *item = [NSPasteboardItem new];
	[(__bridge NSMutableArray *)items addObject:item];
	return (__bridge void *)item;
}

static void pbSetData(void *item, _GoString_ type, const void *bytes, long n) {
	@autoreleasepool {
		NSString *t = [[NSString alloc] initWithBytes:_GoStringPtr(type) length:_GoStringLen(type) encoding:NSUTF8StringEncoding];
		[(__bridge NSPasteboardItem *)item setData:[NSData dataWithBytes:bytes length:n] forType:t];
	}
}

// pbWrite replaces the pasteboard's contents with items, consuming them, and
// returns the changeCount after the write. hostOnly keeps the contents off
// Universal Clipboard.
static long pbWrite(_GoString_ name, void *items, bool hostOnly) {
	@autoreleasepool {
		NSArray *objects = (__bridge_transfer NSArray *)items;
		NSPasteboard *pb = pasteboardNamed(name);
		[pb prepareForNewContentsWithOptions:hostOnly ? NSPasteboardContentsCurrentHostOnly : 0];
		if (objects.count) [pb writeObjects:objects];
		return pb.changeCount;
	}
}
*/
import "C"

import "unsafe"

const (
	utiPlainText = "public.utf8-plain-text"
	utiConcealed = "org.nspasteboard.ConcealedType"
)

type pbEntry struct {
	typ  string
	data []byte
}

// pbItem is one NSPasteboardItem: every type it offers, in its order.
type pbItem []pbEntry

// Pasteboard names below: "" is the general (system) pasteboard.

func changeCount(pasteboard string) int {
	return int(C.pbChangeCount(pasteboard))
}

func readItems(pasteboard string) []pbItem {
	arr := C.pbCopyItems(pasteboard)
	defer C.CFRelease(C.CFTypeRef(arr))
	items := make([]pbItem, C.CFArrayGetCount(arr))
	for i := range items {
		entries := C.CFArrayRef(uintptr(C.CFArrayGetValueAtIndex(arr, C.CFIndex(i))))
		for j := C.CFIndex(0); j < C.CFArrayGetCount(entries); j += 2 {
			items[i] = append(items[i], pbEntry{string(cfData(entries, j)), cfData(entries, j+1)})
		}
	}
	return items
}

func cfData(arr C.CFArrayRef, i C.CFIndex) []byte {
	d := C.CFDataRef(uintptr(C.CFArrayGetValueAtIndex(arr, i)))
	return C.GoBytes(unsafe.Pointer(C.CFDataGetBytePtr(d)), C.int(C.CFDataGetLength(d)))
}

func writeItems(pasteboard string, items []pbItem, hostOnly bool) int {
	arr := C.pbNewItems()
	for _, it := range items {
		item := C.pbAddItem(arr)
		for _, e := range it {
			C.pbSetData(item, e.typ, unsafe.Pointer(unsafe.SliceData(e.data)), C.long(len(e.data)))
		}
	}
	return int(C.pbWrite(pasteboard, arr, C.bool(hostOnly)))
}

// textItem is a plain-text item. A transient one carries the nspasteboard.org
// markers that tell clipboard managers not to record it.
func textItem(text string, transient bool) pbItem {
	item := pbItem{{utiPlainText, []byte(text)}}
	if transient {
		item = append(item, pbEntry{"org.nspasteboard.TransientType", []byte{}}, pbEntry{"org.nspasteboard.AutoGeneratedType", []byte{}})
	}
	return item
}

func concealed(items []pbItem) bool {
	for _, it := range items {
		for _, e := range it {
			if e.typ == utiConcealed {
				return true
			}
		}
	}
	return false
}
