// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteModelByName(arg1) {
  return window['go']['main']['App']['DeleteModelByName'](arg1);
}

export function DeleteTranscript(arg1) {
  return window['go']['main']['App']['DeleteTranscript'](arg1);
}

export function DownloadModel() {
  return window['go']['main']['App']['DownloadModel']();
}

export function DownloadModelByName(arg1) {
  return window['go']['main']['App']['DownloadModelByName'](arg1);
}

export function EnsureWhisperCLI() {
  return window['go']['main']['App']['EnsureWhisperCLI']();
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTranscript(arg1) {
  return window['go']['main']['App']['GetTranscript'](arg1);
}

export function IsModelDownloaded() {
  return window['go']['main']['App']['IsModelDownloaded']();
}

export function IsModelReady() {
  return window['go']['main']['App']['IsModelReady']();
}

export function IsWhisperCLIReady() {
  return window['go']['main']['App']['IsWhisperCLIReady']();
}

export function OpenHistoryWindow() {
  return window['go']['main']['App']['OpenHistoryWindow']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RetryWithGemini(arg1, arg2) {
  return window['go']['main']['App']['RetryWithGemini'](arg1, arg2);
}

export function SearchHistory(arg1, arg2) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetHandsFreeHotkey(arg1) {
  return window['go']['main']['App']['SetHandsFreeHotkey'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetPushToTalkHotkey(arg1) {
  return window['go']['main']['App']['SetPushToTalkHotkey'](arg1);
}

export function SetWhisperModel(arg1) {
  return window['go']['main']['App']['SetWhisperModel'](arg1);
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}
