// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteTranscript(arg1:number):Promise<void>;

export function DownloadModel():Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function GetHistory(arg1:number):Promise<Array<history.Transcript>>;

export function GetStatus():Promise<string>;

export function GetTranscript(arg1:number):Promise<history.Transcript>;

export function IsModelDownloaded():Promise<boolean>;

export function IsModelReady():Promise<boolean>;

export function OpenHistoryWindow():Promise<void>;

export function OpenSettings():Promise<void>;

export function Quit():Promise<void>;

export function RetryWithGemini(arg1:number,arg2:string):Promise<string>;

export function SearchHistory(arg1:string,arg2:number):Promise<Array<history.Transcript>>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetWhisperModel(arg1:string):Promise<void>;

export function StartRecording():Promise<void>;

export function StopRecording():Promise<void>;

export function ToggleRecording():Promise<string>;
