// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {whisper} from '../models';
import {history} from '../models';
import {localgguf} from '../models';

export function CancelDownload():Promise<void>;

export function CancelLocalModelDownload():Promise<void>;

export function CheckCerebrasModel(arg1:string):Promise<main.CheckResult>;

export function CheckGeminiModel(arg1:string):Promise<main.CheckResult>;

export function CheckGroqModel(arg1:string):Promise<main.CheckResult>;

export function CheckLocalModel(arg1:string):Promise<main.CheckResult>;

export function CheckOpenRouterModel(arg1:string):Promise<main.CheckResult>;

export function ClearAllHistory():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteLocalModel(arg1:string):Promise<void>;

export function DeleteModelByName(arg1:string):Promise<void>;

export function DeleteTranscript(arg1:number):Promise<void>;

export function DownloadLocalModel(arg1:string):Promise<void>;

export function DownloadModel():Promise<void>;

export function DownloadModelByName(arg1:string):Promise<void>;

export function EnsureWhisperCLI():Promise<void>;

export function GetActiveLocalDownload():Promise<string>;

export function GetAllModels():Promise<Array<whisper.ModelInfo>>;

export function GetCerebrasModel():Promise<string>;

export function GetCerebrasModelDescriptions():Promise<Record<string, string>>;

export function GetCerebrasModels():Promise<Array<string>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetGeminiModel():Promise<string>;

export function GetGeminiModels():Promise<Array<string>>;

export function GetGroqModel():Promise<string>;

export function GetGroqModelDescriptions():Promise<Record<string, string>>;

export function GetGroqModels():Promise<Array<string>>;

export function GetHistory(arg1:number):Promise<Array<history.Transcript>>;

export function GetLLMProvider():Promise<string>;

export function GetLocalModel():Promise<string>;

export function GetLocalModels():Promise<Array<localgguf.ModelInfo>>;

export function GetOpenRouterModel():Promise<string>;

export function GetOpenRouterModelDescriptions():Promise<Record<string, string>>;

export function GetOpenRouterModels():Promise<Array<string>>;

export function GetStatus():Promise<string>;

export function GetTranscript(arg1:number):Promise<history.Transcript>;

export function HideMiniMode():Promise<void>;

export function IsFullscreen():Promise<boolean>;

export function IsMaximized():Promise<boolean>;

export function IsMiniMode():Promise<boolean>;

export function IsMinimized():Promise<boolean>;

export function IsModelDownloaded():Promise<boolean>;

export function IsModelReady():Promise<boolean>;

export function IsWhisperCLIReady():Promise<boolean>;

export function Minimize():Promise<void>;

export function OpenHistoryWindow():Promise<void>;

export function OpenSettings():Promise<void>;

export function Quit():Promise<void>;

export function RetryWithGemini(arg1:number,arg2:string):Promise<string>;

export function SearchHistory(arg1:string,arg2:number):Promise<Array<history.Transcript>>;

export function SetAPIKey(arg1:string):Promise<void>;

export function SetCerebrasAPIKey(arg1:string):Promise<void>;

export function SetCerebrasModel(arg1:string):Promise<void>;

export function SetGeminiModel(arg1:string):Promise<void>;

export function SetGroqAPIKey(arg1:string):Promise<void>;

export function SetGroqModel(arg1:string):Promise<void>;

export function SetHandsFreeHotkey(arg1:string):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function SetLLMProvider(arg1:string):Promise<void>;

export function SetLocalModel(arg1:string):Promise<void>;

export function SetMiniModeExpanded(arg1:boolean):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetOpenRouterAPIKey(arg1:string):Promise<void>;

export function SetOpenRouterModel(arg1:string):Promise<void>;

export function SetPushToTalkHotkey(arg1:string):Promise<void>;

export function SetWhisperModel(arg1:string):Promise<void>;

export function ShowMiniMode():Promise<void>;

export function StartRecording():Promise<void>;

export function StartStreamingTranscription():Promise<void>;

export function StopRecording():Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function ToggleRecording():Promise<string>;
