// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelLocalModelDownload() {
  return window['go']['main']['App']['CancelLocalModelDownload']();
}

export function CheckCerebrasModel(arg1) {
  return window['go']['main']['App']['CheckCerebrasModel'](arg1);
}

export function CheckGeminiModel(arg1) {
  return window['go']['main']['App']['CheckGeminiModel'](arg1);
}

export function CheckGroqModel(arg1) {
  return window['go']['main']['App']['CheckGroqModel'](arg1);
}

export function CheckLocalModel(arg1) {
  return window['go']['main']['App']['CheckLocalModel'](arg1);
}

export function CheckOpenRouterModel(arg1) {
  return window['go']['main']['App']['CheckOpenRouterModel'](arg1);
}

export function ClearAllHistory() {
  return window['go']['main']['App']['ClearAllHistory']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteLocalModel(arg1) {
  return window['go']['main']['App']['DeleteLocalModel'](arg1);
}

export function DeleteModelByName(arg1) {
  return window['go']['main']['App']['DeleteModelByName'](arg1);
}

export function DeleteTranscript(arg1) {
  return window['go']['main']['App']['DeleteTranscript'](arg1);
}

export function DownloadLocalModel(arg1) {
  return window['go']['main']['App']['DownloadLocalModel'](arg1);
}

export function DownloadModel() {
  return window['go']['main']['App']['DownloadModel']();
}

export function DownloadModelByName(arg1) {
  return window['go']['main']['App']['DownloadModelByName'](arg1);
}

export function EnsureWhisperCLI() {
  return window['go']['main']['App']['EnsureWhisperCLI']();
}

export function GetActiveLocalDownload() {
  return window['go']['main']['App']['GetActiveLocalDownload']();
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetCerebrasModel() {
  return window['go']['main']['App']['GetCerebrasModel']();
}

export function GetCerebrasModelDescriptions() {
  return window['go']['main']['App']['GetCerebrasModelDescriptions']();
}

export function GetCerebrasModels() {
  return window['go']['main']['App']['GetCerebrasModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetGeminiModel() {
  return window['go']['main']['App']['GetGeminiModel']();
}

export function GetGeminiModels() {
  return window['go']['main']['App']['GetGeminiModels']();
}

export function GetGroqModel() {
  return window['go']['main']['App']['GetGroqModel']();
}

export function GetGroqModelDescriptions() {
  return window['go']['main']['App']['GetGroqModelDescriptions']();
}

export function GetGroqModels() {
  return window['go']['main']['App']['GetGroqModels']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetLLMProvider() {
  return window['go']['main']['App']['GetLLMProvider']();
}

export function GetLocalModel() {
  return window['go']['main']['App']['GetLocalModel']();
}

export function GetLocalModels() {
  return window['go']['main']['App']['GetLocalModels']();
}

export function GetOpenRouterModel() {
  return window['go']['main']['App']['GetOpenRouterModel']();
}

export function GetOpenRouterModelDescriptions() {
  return window['go']['main']['App']['GetOpenRouterModelDescriptions']();
}

export function GetOpenRouterModels() {
  return window['go']['main']['App']['GetOpenRouterModels']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTranscript(arg1) {
  return window['go']['main']['App']['GetTranscript'](arg1);
}

export function HideMiniMode() {
  return window['go']['main']['App']['HideMiniMode']();
}

export function IsFullscreen() {
  return window['go']['main']['App']['IsFullscreen']();
}

export function IsMaximized() {
  return window['go']['main']['App']['IsMaximized']();
}

export function IsMiniMode() {
  return window['go']['main']['App']['IsMiniMode']();
}

export function IsMinimized() {
  return window['go']['main']['App']['IsMinimized']();
}

export function IsModelDownloaded() {
  return window['go']['main']['App']['IsModelDownloaded']();
}

export function IsModelReady() {
  return window['go']['main']['App']['IsModelReady']();
}

export function IsWhisperCLIReady() {
  return window['go']['main']['App']['IsWhisperCLIReady']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function OpenHistoryWindow() {
  return window['go']['main']['App']['OpenHistoryWindow']();
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RetryWithGemini(arg1, arg2) {
  return window['go']['main']['App']['RetryWithGemini'](arg1, arg2);
}

export function SearchHistory(arg1, arg2) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetCerebrasAPIKey(arg1) {
  return window['go']['main']['App']['SetCerebrasAPIKey'](arg1);
}

export function SetCerebrasModel(arg1) {
  return window['go']['main']['App']['SetCerebrasModel'](arg1);
}

export function SetGeminiModel(arg1) {
  return window['go']['main']['App']['SetGeminiModel'](arg1);
}

export function SetGroqAPIKey(arg1) {
  return window['go']['main']['App']['SetGroqAPIKey'](arg1);
}

export function SetGroqModel(arg1) {
  return window['go']['main']['App']['SetGroqModel'](arg1);
}

export function SetHandsFreeHotkey(arg1) {
  return window['go']['main']['App']['SetHandsFreeHotkey'](arg1);
}

export function SetHotkey(arg1) {
  return window['go']['main']['App']['SetHotkey'](arg1);
}

export function SetLLMProvider(arg1) {
  return window['go']['main']['App']['SetLLMProvider'](arg1);
}

export function SetLocalModel(arg1) {
  return window['go']['main']['App']['SetLocalModel'](arg1);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function SetOpenRouterAPIKey(arg1) {
  return window['go']['main']['App']['SetOpenRouterAPIKey'](arg1);
}

export function SetOpenRouterModel(arg1) {
  return window['go']['main']['App']['SetOpenRouterModel'](arg1);
}

export function SetPushToTalkHotkey(arg1) {
  return window['go']['main']['App']['SetPushToTalkHotkey'](arg1);
}

export function SetWhisperModel(arg1) {
  return window['go']['main']['App']['SetWhisperModel'](arg1);
}

export function ShowMiniMode() {
  return window['go']['main']['App']['ShowMiniMode']();
}

export function StartRecording() {
  return window['go']['main']['App']['StartRecording']();
}

export function StopRecording() {
  return window['go']['main']['App']['StopRecording']();
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}
