// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function CancelRecording() {
  return window['go']['main']['App']['CancelRecording']();
}

export function CheckCerebrasModel(arg1) {
  return window['go']['main']['App']['CheckCerebrasModel'](arg1);
}

export function CheckGeminiModel(arg1) {
  return window['go']['main']['App']['CheckGeminiModel'](arg1);
}

export function CheckGroqModel(arg1) {
  return window['go']['main']['App']['CheckGroqModel'](arg1);
}

export function CheckLocalModel(arg1) {
  return window['go']['main']['App']['CheckLocalModel'](arg1);
}

export function CheckOpenRouterModel(arg1) {
  return window['go']['main']['App']['CheckOpenRouterModel'](arg1);
}

export function CheckProviderModel(arg1, arg2) {
  return window['go']['main']['App']['CheckProviderModel'](arg1, arg2);
}

export function ClearAllHistory() {
  return window['go']['main']['App']['ClearAllHistory']();
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteModelByName(arg1) {
  return window['go']['main']['App']['DeleteModelByName'](arg1);
}

export function DeleteTranscript(arg1) {
  return window['go']['main']['App']['DeleteTranscript'](arg1);
}

export function DownloadModel() {
  return window['go']['main']['App']['DownloadModel']();
}

export function DownloadModelByName(arg1) {
  return window['go']['main']['App']['DownloadModelByName'](arg1);
}

export function GetAllModels() {
  return window['go']['main']['App']['GetAllModels']();
}

export function GetAppRules() {
  return window['go']['main']['App']['GetAppRules']();
}

export function GetCerebrasModels() {
  return window['go']['main']['App']['GetCerebrasModels']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFrontmostApp() {
  return window['go']['main']['App']['GetFrontmostApp']();
}

export function GetGeminiModels() {
  return window['go']['main']['App']['GetGeminiModels']();
}

export function GetGroqModels() {
  return window['go']['main']['App']['GetGroqModels']();
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetHistoryPage(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetHistoryPage'](arg1, arg2, arg3);
}

export function GetInputDevices() {
  return window['go']['main']['App']['GetInputDevices']();
}

export function GetOnboardingCompleted() {
  return window['go']['main']['App']['GetOnboardingCompleted']();
}

export function GetOpenRouterModels() {
  return window['go']['main']['App']['GetOpenRouterModels']();
}

export function GetPermissions() {
  return window['go']['main']['App']['GetPermissions']();
}

export function GetProviderModels(arg1) {
  return window['go']['main']['App']['GetProviderModels'](arg1);
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetPushToTalkKey() {
  return window['go']['main']['App']['GetPushToTalkKey']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetUpdateInfo() {
  return window['go']['main']['App']['GetUpdateInfo']();
}

export function HideMiniMode() {
  return window['go']['main']['App']['HideMiniMode']();
}

export function InjectText(arg1) {
  return window['go']['main']['App']['InjectText'](arg1);
}

export function IsAccessibilityGranted() {
  return window['go']['main']['App']['IsAccessibilityGranted']();
}

export function IsMiniMode() {
  return window['go']['main']['App']['IsMiniMode']();
}

export function IsModelDownloaded() {
  return window['go']['main']['App']['IsModelDownloaded']();
}

export function IsModelReady() {
  return window['go']['main']['App']['IsModelReady']();
}

export function IsWhisperCLIReady() {
  return window['go']['main']['App']['IsWhisperCLIReady']();
}

export function LogFrontendError(arg1, arg2) {
  return window['go']['main']['App']['LogFrontendError'](arg1, arg2);
}

export function OpenHistoryWindow() {
  return window['go']['main']['App']['OpenHistoryWindow']();
}

export function OpenPrivacySettings(arg1) {
  return window['go']['main']['App']['OpenPrivacySettings'](arg1);
}

export function OpenSettings() {
  return window['go']['main']['App']['OpenSettings']();
}

export function PromptAccessibilityExplanation() {
  return window['go']['main']['App']['PromptAccessibilityExplanation']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RemoveAppRule(arg1) {
  return window['go']['main']['App']['RemoveAppRule'](arg1);
}

export function RequestMicrophoneAccess() {
  return window['go']['main']['App']['RequestMicrophoneAccess']();
}

export function ResetWindowPosition() {
  return window['go']['main']['App']['ResetWindowPosition']();
}

export function RetryRefinement(arg1, arg2) {
  return window['go']['main']['App']['RetryRefinement'](arg1, arg2);
}

export function SearchHistoryPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchHistoryPage'](arg1, arg2, arg3, arg4);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function SetAppRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAppRule'](arg1, arg2, arg3);
}

export function SetCerebrasAPIKey(arg1) {
  return window['go']['main']['App']['SetCerebrasAPIKey'](arg1);
}

export function SetCerebrasModel(arg1) {
  return window['go']['main']['App']['SetCerebrasModel'](arg1);
}

export function SetGeminiModel(arg1) {
  return window['go']['main']['App']['SetGeminiModel'](arg1);
}

export function SetGroqAPIKey(arg1) {
  return window['go']['main']['App']['SetGroqAPIKey'](arg1);
}

export function SetGroqModel(arg1) {
  return window['go']['main']['App']['SetGroqModel'](arg1);
}

export function SetHandsFreeHotkey(arg1) {
  return window['go']['main']['App']['SetHandsFreeHotkey'](arg1);
}

export function SetInputDevice(arg1) {
  return window['go']['main']['App']['SetInputDevice'](arg1);
}

export function SetLLMProvider(arg1) {
  return window['go']['main']['App']['SetLLMProvider'](arg1);
}

export function SetLocalModel(arg1) {
  return window['go']['main']['App']['SetLocalModel'](arg1);
}

export function SetLocalURL(arg1) {
  return window['go']['main']['App']['SetLocalURL'](arg1);
}

export function SetMiniModeExpanded(arg1, arg2) {
  return window['go']['main']['App']['SetMiniModeExpanded'](arg1, arg2);
}

export function SetMuteSystemAudio(arg1) {
  return window['go']['main']['App']['SetMuteSystemAudio'](arg1);
}

export function SetOpenRouterAPIKey(arg1) {
  return window['go']['main']['App']['SetOpenRouterAPIKey'](arg1);
}

export function SetOpenRouterModel(arg1) {
  return window['go']['main']['App']['SetOpenRouterModel'](arg1);
}

export function SetProvider(arg1) {
  return window['go']['main']['App']['SetProvider'](arg1);
}

export function SetProviderAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetProviderAPIKey'](arg1, arg2);
}

export function SetProviderModel(arg1, arg2) {
  return window['go']['main']['App']['SetProviderModel'](arg1, arg2);
}

export function SetPushToTalkHotkey(arg1) {
  return window['go']['main']['App']['SetPushToTalkHotkey'](arg1);
}

export function SetPushToTalkKey(arg1) {
  return window['go']['main']['App']['SetPushToTalkKey'](arg1);
}

export function SetRefinementMode(arg1) {
  return window['go']['main']['App']['SetRefinementMode'](arg1);
}

export function SetVocabulary(arg1) {
  return window['go']['main']['App']['SetVocabulary'](arg1);
}

export function SetWhisperLanguage(arg1) {
  return window['go']['main']['App']['SetWhisperLanguage'](arg1);
}

export function SetWhisperModel(arg1) {
  return window['go']['main']['App']['SetWhisperModel'](arg1);
}

export function ShowMiniMode() {
  return window['go']['main']['App']['ShowMiniMode']();
}

export function SuspendHotkeys(arg1) {
  return window['go']['main']['App']['SuspendHotkeys'](arg1);
}

export function ToggleRecording() {
  return window['go']['main']['App']['ToggleRecording']();
}
