// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {whisper} from '../models';
import {history} from '../models';
import {audio} from '../models';
import {update} from '../models';

export function CancelDownload():Promise<void>;

export function CancelRecording():Promise<void>;

export function CheckProviderModel(arg1:string,arg2:string):Promise<main.CheckResult>;

export function ClearAllHistory():Promise<void>;

export function CompleteOnboarding():Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteModelByName(arg1:string):Promise<void>;

export function DeleteTranscript(arg1:number):Promise<void>;

export function DownloadModel():Promise<void>;

export function DownloadModelByName(arg1:string):Promise<void>;

export function GetActiveDownload():Promise<main.modelDownloadEvent>;

export function GetAllModels():Promise<Array<whisper.ModelInfo>>;

export function GetAppRules():Promise<Array<main.AppRuleDTO>>;

export function GetConfig():Promise<main.ConfigResponse>;

export function GetFrontmostApp():Promise<main.FrontmostAppInfo>;

export function GetHistory(arg1:number):Promise<Array<history.Transcript>>;

export function GetHistoryPage(arg1:string,arg2:number,arg3:number):Promise<main.HistoryPage>;

export function GetInputDevices():Promise<Array<audio.InputDevice>>;

export function GetOnboardingCompleted():Promise<boolean>;

export function GetPermissions():Promise<main.Permissions>;

export function GetProviderModels(arg1:string):Promise<Array<string>>;

export function GetProviders():Promise<Array<main.ProviderInfo>>;

export function GetPushToTalkKey():Promise<main.PushToTalkKeyInfo>;

export function GetStatus():Promise<string>;

export function GetUpdateInfo():Promise<update.Info>;

export function HideMiniMode():Promise<void>;

export function InjectText(arg1:string):Promise<void>;

export function IsAccessibilityGranted():Promise<boolean>;

export function IsMiniMode():Promise<boolean>;

export function IsModelDownloaded():Promise<boolean>;

export function IsModelReady():Promise<boolean>;

export function IsWhisperCLIReady():Promise<boolean>;

export function LogFrontendError(arg1:string,arg2:string):Promise<void>;

export function OpenHistoryWindow():Promise<void>;

export function OpenLogFile():Promise<void>;

export function OpenPrivacySettings(arg1:string):Promise<void>;

export function OpenSettings():Promise<void>;

export function PromptAccessibilityExplanation():Promise<boolean>;

export function Quit():Promise<void>;

export function RemoveAppRule(arg1:string):Promise<void>;

export function RequestMicrophoneAccess():Promise<boolean>;

export function ResetWindowPosition():Promise<void>;

export function RetryRefinement(arg1:number,arg2:string):Promise<string>;

export function SearchHistoryPage(arg1:string,arg2:string,arg3:number,arg4:number):Promise<main.HistoryPage>;

export function SetAppRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetEditHotkey(arg1:string):Promise<void>;

export function SetHandsFreeHotkey(arg1:string):Promise<void>;

export function SetInputDevice(arg1:string):Promise<void>;

export function SetLocalURL(arg1:string):Promise<void>;

export function SetMiniModeExpanded(arg1:boolean,arg2:number):Promise<void>;

export function SetMuteSystemAudio(arg1:boolean):Promise<void>;

export function SetProvider(arg1:string):Promise<void>;

export function SetProviderAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetProviderModel(arg1:string,arg2:string):Promise<void>;

export function SetPushToTalkHotkey(arg1:string):Promise<void>;

export function SetPushToTalkKey(arg1:string):Promise<main.PushToTalkKeyInfo>;

export function SetRefinementMode(arg1:string):Promise<void>;

export function SetVocabulary(arg1:string):Promise<void>;

export function SetWhisperLanguage(arg1:string):Promise<void>;

export function SetWhisperModel(arg1:string):Promise<void>;

export function ShowMiniMode():Promise<void>;

export function SuspendHotkeys(arg1:boolean):Promise<void>;

export function ToggleRecording():Promise<string>;
